[package]
name = "ev3-dc"
version = "0.1.0"
edition = "2024"
license = "MIT"
keywords = [ "ev3", "command" ]
categories = [ "science::robotics" ]

[dependencies]
displaystr = "0.1.11"
# thiserror = "2.0.17"

[dev-dependencies]
hidapi = "2.6.3"

# [profile.release]
# debug = true
